spring.application.name=food-order-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/restaurant_info
spring.datasource.username=root
spring.datasource.password=ashu1225
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.session.jdbc.initialize-schema=always


spring.mvc.hiddenmethod.filter.enabled=true
